version: 0.0
os: linux
files:
  - source: /
    destination: /opt/bitnami/wordpress/wp-content/themes/2hatslogic2024
file_exists_behavior: OVERWRITE
permissions:
  - object: /opt/bitnami/wordpress/wp-content/themes/2hatslogic2024
    owner: bitnami
    group: daemon
    type:
      - file
      - directory
hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: bitnami
