version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/2hatslogic-wp/wp-content/themes/2hatslogic2024
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html/2hatslogic-wp/wp-content/themes/2hatslogic2024
    owner: bitnami
    group: daemon
    type:
      - file
      - directory
hooks:
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: bitnami
      commands:
        - command: /bin/bash scripts/AfterInstall.sh